apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 3000  # Port on which the service is exposed
      targetPort: 3000  # Port the web server containers are listening on
  type: LoadBalancer  # Use 'LoadBalancer' if running on a cloud provider; use 'NodePort' for local testing
